name: 02-workflow-events
on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch: 

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Triggered by ${{github.event_name}}"