name: 04 - Github-Remote
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies          
              run: |
                pwd
                ls
                cd github_actions
                ls
                cd react-app
                pwd
                npm ci
            - name: Run Unittests
              run: npm run test              
